name: GuestBook CI/CD Pipeline

on:
  push:

jobs:
  ci-job:
    runs-on: ubuntu-latest
    steps:
    - name: Check Out
      uses: actions/checkout@v3

    - name: 소스코드 확인
      run: |
        tree -L 5 ~/work/guestbook
